# Generated by Django 5.1 on 2026-09-17 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='color_hex',
            field=models.CharField(default='#5b7a5e', help_text="Used to color this member's cards in the weekly household plan view.", max_length=7),
        ),
        migrations.CreateModel(
            name='HouseholdTaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('starts_on', models.DateField(help_text='Anchor date the recurrence rule is expanded from.')),
                ('recurrence_rule', models.CharField(help_text='RFC 5545 RRULE string, e.g. FREQ=WEEKLY;BYDAY=MO or FREQ=MONTHLY;BYDAY=1MO', max_length=500)),
                ('system_action', models.CharField(choices=[('none', 'None'), ('weekly_household_planning', 'Weekly household planning'), ('weekly_meal_planning', 'Weekly meal planning')], default='none', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assigned_task_definitions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='HouseholdTaskInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('snoozed', 'Snoozed')], default='pending', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_instances', to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='household.householdtaskdefinition')),
            ],
            options={
                'ordering': ['scheduled_date'],
                'unique_together': {('definition', 'scheduled_date')},
            },
        ),
        migrations.CreateModel(
            name='HouseholdTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('reassigned', 'Reassigned'), ('snoozed', 'Snoozed'), ('postponed', 'Postponed'), ('completed', 'Completed')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='household.householdtaskinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='HouseholdTask',
        ),
    ]
