# Generated by Django 5.1 on 2026-09-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_householdmember_color_hex_householdtaskdefinition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdtaskdefinition',
            name='icon',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('trash', 'Trash'), ('coffee', 'Coffee'), ('laundry', 'Laundry'), ('dishes', 'Dishes'), ('vacuum', 'Vacuum'), ('shopping', 'Shopping'), ('plant', 'Plant'), ('pet', 'Pet'), ('tool', 'Repair'), ('bed', 'Bed'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
