# Generated by Django 5.2.17 on 2026-09-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_householdtaskdefinition_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='householdtaskdefinition',
            name='assignment_mode',
            field=models.CharField(choices=[('fixed', 'Fixed member'), ('alternating', 'Alternate between members'), ('none', 'Decide during planning')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='householdtaskdefinition',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Time of day this recurs at -- currently only surfaced for the weekly planning reminder; not yet wired to notifications.', null=True),
        ),
        migrations.AlterField(
            model_name='householdtaskdefinition',
            name='default_assignee',
            field=models.ForeignKey(blank=True, help_text="Only used when assignment_mode is 'fixed'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assigned_task_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='householdtaskdefinition',
            name='icon',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('trash', 'Trash'), ('coffee', 'Coffee'), ('laundry', 'Laundry'), ('dishes', 'Dishes'), ('vacuum', 'Vacuum'), ('shopping', 'Shopping'), ('plant', 'Plant'), ('pet', 'Pet'), ('tool', 'Repair'), ('bed', 'Bed'), ('calendar', 'Calendar'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
