# Generated by Django 5.2.17 on 2026-09-17 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_householdtaskdefinition_assignment_mode_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='householdtaskinstance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='householdtaskdefinition',
            name='has_preferred_day',
            field=models.BooleanField(default=True, help_text='If false, occurrences land in the backlog (no day) until dragged onto one during planning.'),
        ),
        migrations.AddField(
            model_name='householdtaskinstance',
            name='is_in_backlog',
            field=models.BooleanField(default=False, help_text="Shown in the backlog lane (no day yet) instead of under scheduled_date's weekday."),
        ),
        migrations.AddField(
            model_name='householdtaskinstance',
            name='occurrence_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='householdtaskinstance',
            name='standalone_icon',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('trash', 'Trash'), ('coffee', 'Coffee'), ('laundry', 'Laundry'), ('dishes', 'Dishes'), ('vacuum', 'Vacuum'), ('shopping', 'Shopping'), ('plant', 'Plant'), ('pet', 'Pet'), ('tool', 'Repair'), ('bed', 'Bed'), ('calendar', 'Calendar'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='householdtaskinstance',
            name='standalone_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='householdtaskevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('reassigned', 'Reassigned'), ('snoozed', 'Snoozed to backlog'), ('skipped', 'Skipped this occurrence'), ('postponed', 'Postponed'), ('completed', 'Completed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='household.householdtaskdefinition'),
        ),
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', max_length=10),
        ),
    ]
