# Generated by Django 5.2.17 on 2026-09-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0008_householdsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdmember',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
