# Generated by Django 5.2.17 on 2026-09-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0009_householdmember_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdsettings',
            name='timezone',
            field=models.CharField(default='Europe/Berlin', max_length=50),
        ),
        migrations.AlterField(
            model_name='householdtaskevent',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('reassigned', 'Reassigned'), ('snoozed', 'Snoozed to backlog'), ('skipped', 'Skipped this occurrence'), ('postponed', 'Postponed'), ('completed', 'Completed'), ('reopened', 'Reopened (undo)')], max_length=15),
        ),
    ]
