# Generated by Django 5.2.17 on 2026-09-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0011_householdtaskinstance_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed')], default='pending', max_length=10),
        ),
    ]
