# Generated by Django 5.2.17 on 2026-09-17 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0012_alter_householdtaskinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='householdtaskinstance',
            name='origin_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snoozed_copies', to='household.householdtaskinstance'),
        ),
        migrations.AddField(
            model_name='householdtaskinstance',
            name='system_action',
            field=models.CharField(choices=[('none', 'None'), ('weekly_household_planning', 'Weekly household planning'), ('weekly_meal_planning', 'Weekly meal planning')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
