# Generated by Django 5.2.17 on 2026-09-18 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0015_pushsubscription_notificationlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('received_from', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['valid_until'],
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('amount_used', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remaining_after', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='household.voucher')),
            ],
            options={
                'ordering': ['-redeemed_on', '-id'],
            },
        ),
    ]
