# Generated by Django 5.2.17 on 2026-09-20 15:09

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0019_finalize_recipes_and_shopping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cooked', models.DateField(default=django.utils.timezone.localdate)),
                ('servings_made', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_cooked', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['name_de']},
        ),
        migrations.AlterModelOptions(
            name='mealtimecategory',
            options={'ordering': ['sort_order', 'name_de'], 'verbose_name_plural': 'meal time categories'},
        ),
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['sort_order', 'name_de']},
        ),
        migrations.RemoveConstraint(
            model_name='label',
            name='unique_label_name_ci',
        ),
        migrations.RemoveConstraint(
            model_name='mealtimecategory',
            name='unique_meal_category_name_ci',
        ),
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='mealtimecategory',
            old_name='name',
            new_name='name_de',
        ),
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='abbreviation',
            new_name='abbreviation_de',
        ),
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='name',
            new_name='name_de',
        ),
        migrations.AddField(
            model_name='label',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mealtimecategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='abbreviation_en',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_de'), name='unique_label_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='mealtimecategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name_de'), name='unique_meal_category_name_ci'),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='logged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mealevent',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_events', to='household.recipe'),
        ),
    ]
