# Generated by Django 5.2.17 on 2026-09-20 16:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill_completed_items(apps, schema_editor):
    """Items already ticked off before this existed would otherwise never
    show up in the history; date them by when they were last touched."""
    ShoppingListItem = apps.get_model('household', 'ShoppingListItem')
    PurchaseRecord = apps.get_model('household', 'PurchaseRecord')
    for item in ShoppingListItem.objects.filter(is_completed=True).select_related('shopping_list'):
        PurchaseRecord.objects.create(
            title=item.title, quantity=item.quantity, unit=item.unit, ingredient=item.ingredient,
            list_name=item.shopping_list.name, purchased_on=item.updated_at.date(),
            purchased_by=item.created_by, item=item,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0021_seed_english_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('list_name', models.CharField(blank=True, max_length=100)),
                ('purchased_on', models.DateField(default=django.utils.timezone.localdate)),
                ('ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='household.ingredient')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='household.shoppinglistitem')),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='household.unitofmeasure')),
            ],
            options={
                'ordering': ['-purchased_on', '-id'],
            },
        ),
        migrations.RunPython(backfill_completed_items, migrations.RunPython.noop),
    ]
