# Generated by Django 5.2.17 on 2026-09-20 16:20

import django.db.models.deletion
from django.db import migrations, models


def assign_lists(apps, schema_editor):
    """Records made before per-list history: use the item's list while the
    item still exists, else the list with the same name if that's unambiguous."""
    PurchaseRecord = apps.get_model('household', 'PurchaseRecord')
    ShoppingList = apps.get_model('household', 'ShoppingList')
    for record in PurchaseRecord.objects.filter(shopping_list__isnull=True).select_related('item'):
        if record.item_id:
            record.shopping_list_id = record.item.shopping_list_id
        else:
            matches = list(ShoppingList.objects.filter(name=record.list_name)[:2])
            if len(matches) != 1:
                continue
            record.shopping_list_id = matches[0].id
        record.save(update_fields=['shopping_list'])


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0022_purchase_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='shopping_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_records', to='household.shoppinglist'),
        ),
        migrations.RunPython(assign_lists, migrations.RunPython.noop),
    ]
