# Generated by Django 5.2.17 on 2026-09-20 17:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0023_purchase_record_shopping_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='householdtaskdefinition',
            name='icon',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('trash', 'Trash'), ('coffee', 'Coffee'), ('laundry', 'Laundry'), ('dishes', 'Dishes'), ('vacuum', 'Vacuum'), ('shopping', 'Shopping'), ('plant', 'Plant'), ('pet', 'Pet'), ('tool', 'Repair'), ('bed', 'Bed'), ('calendar', 'Calendar'), ('cooking', 'Cooking'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='householdtaskdefinition',
            name='system_action',
            field=models.CharField(choices=[('none', 'None'), ('weekly_household_planning', 'Weekly household planning'), ('weekly_meal_planning', 'Weekly meal planning'), ('cook_meal', 'Cook a planned meal')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='standalone_icon',
            field=models.CharField(blank=True, choices=[('cleaning', 'Cleaning'), ('trash', 'Trash'), ('coffee', 'Coffee'), ('laundry', 'Laundry'), ('dishes', 'Dishes'), ('vacuum', 'Vacuum'), ('shopping', 'Shopping'), ('plant', 'Plant'), ('pet', 'Pet'), ('tool', 'Repair'), ('bed', 'Bed'), ('calendar', 'Calendar'), ('cooking', 'Cooking'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='householdtaskinstance',
            name='system_action',
            field=models.CharField(choices=[('none', 'None'), ('weekly_household_planning', 'Weekly household planning'), ('weekly_meal_planning', 'Weekly meal planning'), ('cook_meal', 'Cook a planned meal')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today')], max_length=30),
        ),
        migrations.CreateModel(
            name='CookingPlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('top_rating_percentile', models.PositiveSmallIntegerField(default=30, help_text='The best-rated N% of recipes form the "best rated" suggestions.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('uncooked_threshold_days', models.PositiveIntegerField(default=21, help_text='Recipes not cooked for at least this many days count as "not cooked in a while".')),
                ('rating_weight', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0)])),
                ('neglect_weight', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0)])),
                ('craving_count', models.PositiveSmallIntegerField(default=5, help_text='How many "craving" suggestions to show.')),
                ('random_count', models.PositiveSmallIntegerField(default=3, help_text='How many random suggestions to show before the rest.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('planned_meal_categories', models.ManyToManyField(blank=True, help_text='The meals shown as rows in the weekly plan (e.g. lunch and dinner).', related_name='+', to='household.mealtimecategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CookingPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('cook', 'Cook'), ('leftovers', 'Leftovers')], default='cook', max_length=10)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meal_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_entries', to='household.mealtimecategory')),
                ('meal_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='household.mealevent')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='household.recipe')),
                ('source_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leftover_entries', to='household.cookingplanentry')),
                ('task_instance', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cooking_entry', to='household.householdtaskinstance')),
            ],
            options={
                'verbose_name_plural': 'cooking plan entries',
                'ordering': ['date', 'meal_category__sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='CookingPlan',
        ),
    ]
