# Generated by Django 5.2.17 on 2026-09-21 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0024_cooking_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingplanentry',
            name='title',
            field=models.CharField(blank=True, help_text='Only for free dishes without a recipe.', max_length=200),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='notification_language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2),
        ),
        migrations.AlterField(
            model_name='cookingplanentry',
            name='kind',
            field=models.CharField(choices=[('cook', 'Cook'), ('leftovers', 'Leftovers'), ('free', 'Free dish (no recipe)')], default='cook', max_length=10),
        ),
        migrations.AlterField(
            model_name='cookingplanentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_entries', to='household.recipe'),
        ),
    ]
