# Generated by Django 5.2.17 on 2026-09-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0025_free_dishes_and_notification_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingplanentry',
            name='shopping_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
