# Generated by Django 5.2.17 on 2026-09-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0027_packinglist_packingbucket_packingbucketitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='added_buckets',
            field=models.ManyToManyField(blank=True, related_name='+', to='household.packingbucket'),
        ),
    ]
