# Generated by Django 5.2.17 on 2026-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0028_packinglist_added_buckets'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglist',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
