# Generated by Django 5.2.17 on 2026-09-28 02:16
# Hand-fixed: makemigrations produced Remove+Add for source_url->source,
# which would have dropped every recipe's existing link. Rename preserves it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0029_packinglist_is_archived'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='source_url',
            new_name='source',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('website', 'Website'), ('photo', 'Photo'), ('instagram', 'Instagram')], default='manual', max_length=20),
        ),
    ]
