# Generated by Django 5.2.17 on 2026-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0031_googlecalendarlink_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='color_hex',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
