# Generated by Django 5.2.17 on 2026-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0034_seed_ingredient_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='color_hex',
            field=models.CharField(default='#9e9e9e', max_length=7),
        ),
        migrations.AddField(
            model_name='ingredientcategory',
            name='icon',
            field=models.CharField(choices=[('produce', 'Produce'), ('bakery', 'Bakery'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('frozen', 'Frozen'), ('pantry', 'Pantry'), ('spices', 'Spices'), ('drinks', 'Drinks'), ('sweets', 'Sweets'), ('household', 'Household'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
