# Generated by Django 5.2.17 on 2026-10-01 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0036_seed_ingredient_category_icons_and_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('website', 'Website'), ('photo', 'Photo'), ('instagram', 'Instagram'), ('social', 'Social media')], default='manual', max_length=20),
        ),
    ]
