# Generated by Django 5.2.17 on 2026-10-01 17:18

from django.db import migrations, models


def instagram_to_text(apps, schema_editor):
    """'instagram' is replaced by 'text' (paste-text import) and 'social'
    (video import) -- any existing rows become 'text', the closer match
    (both are "pasted/typed content", vs. a downloaded+transcribed video)."""
    Recipe = apps.get_model('household', 'Recipe')
    Recipe.objects.filter(source_type='instagram').update(source_type='text')


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0037_alter_recipe_source_type'),
    ]

    operations = [
        migrations.RunPython(instagram_to_text, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='recipe',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('website', 'Website'), ('photo', 'Photo'), ('text', 'Pasted text'), ('social', 'Social media')], default='manual', max_length=20),
        ),
    ]
