# Generated by Django 5.2.17 on 2026-10-01 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0038_alter_recipe_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationlog',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='reference_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today'), ('voucher_expiring_soon', 'Voucher expiring soon'), ('packing_trip_tomorrow', 'Packing trip starting tomorrow')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='task_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='household.householdtaskinstance'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today'), ('voucher_expiring_soon', 'Voucher expiring soon'), ('packing_trip_tomorrow', 'Packing trip starting tomorrow')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('task_instance__isnull', False)), fields=('task_instance', 'user', 'notification_type', 'channel'), name='unique_task_notification'),
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_key', ''), _negated=True), fields=('reference_key', 'user', 'notification_type', 'channel'), name='unique_reference_notification'),
        ),
    ]
