# Generated by Django 5.2.17 on 2026-10-01 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0039_alter_notificationlog_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('task_overdue', 'Task overdue'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today'), ('voucher_expiring_soon', 'Voucher expiring soon'), ('packing_trip_tomorrow', 'Packing trip starting tomorrow'), ('shopping_purchased', 'Shopping purchased'), ('shopping_items_added', 'New shopping list items')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('task_due_today', 'Task due today'), ('task_overdue', 'Task overdue'), ('household_planning_due', 'Weekly household planning due'), ('meal_planning_due', 'Weekly meal planning due'), ('cooking_today', 'Cooking today'), ('voucher_expiring_soon', 'Voucher expiring soon'), ('packing_trip_tomorrow', 'Packing trip starting tomorrow'), ('shopping_purchased', 'Shopping purchased'), ('shopping_items_added', 'New shopping list items')], max_length=30),
        ),
    ]
