# Generated by Django 5.2.17 on 2026-10-08 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0040_purchaserecord_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packingbucketitem',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='packing_bucket_item_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packingbucketitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='packing_list_item_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
