# Generated by Django 5.2.17 on 2026-10-09 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fan_out_assignees(apps, schema_editor):
    """The old assignees (M2M) -> new assigned_to (single FK) switch: an
    item with multiple assignees becomes multiple items, one per person
    (same text/quantity/packing_list or bucket), since a single row can now
    only name one person. An item with zero or one assignee just gets that
    one value (or stays unassigned) -- no new rows needed."""
    PackingListItem = apps.get_model('household', 'PackingListItem')
    PackingBucketItem = apps.get_model('household', 'PackingBucketItem')
    for Model in (PackingListItem, PackingBucketItem):
        for item in list(Model.objects.prefetch_related('assignees').all()):
            assignee_ids = list(item.assignees.values_list('id', flat=True))
            if not assignee_ids:
                continue
            first_id, *extra_ids = assignee_ids
            Model.objects.filter(pk=item.pk).update(assigned_to_id=first_id)
            for extra_id in extra_ids:
                item.pk = None
                item.id = None
                item.assigned_to_id = extra_id
                item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0041_packingbucketitem_assignees_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='packingbucketitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_bucket_item_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packinglistitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_list_item_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(fan_out_assignees, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='packingbucketitem',
            name='assignees',
        ),
        migrations.RemoveField(
            model_name='packinglistitem',
            name='assignees',
        ),
    ]
