# Generated by Django 5.2.17 on 2026-10-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0042_remove_packingbucketitem_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingplanconfig',
            name='long_ago_count',
            field=models.PositiveSmallIntegerField(default=10, help_text='How many "not cooked in a while" suggestions to show.'),
        ),
    ]
